analytics: {}
color:
  brandColors:
    - '#ffffff'
    - '#8ec641'
    - '#1bb3e4'
    - '#000000'
    - '#4f4f4f'
  brandStrength: 0.271959
  lightness: 0.5
  rhythmicContrast: 0.75
  saturation: 0.75
cta: {}
layout_spectrum: 1
name: YourStudio
opengraph: {}
purpose: []
typography_spectrum: 0
