name: YourStudio
favicon: null
layout_spectrum: 1
typography_spectrum: 0
title: Your Studio Media Productions
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8ec641'
    - '#1bb3e4'
    - '#000000'
    - '#4f4f4f'
  brandStrength: 0.271959
  lightness: 0.5
  saturation: 0.75
  rhythmicContrast: 0.75
purpose: []
